/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.neo.database.jooq;


import net.johanbasson.neo.database.jooq.tables.FlywaySchemaHistory;
import net.johanbasson.neo.database.jooq.tables.Users;


/**
 * Convenience access to all tables in neo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>neo.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>neo.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
